//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShop.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Cake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cake()
        {
            this.OrderDetails = new ObservableCollection<OrderDetail>();
        }
        public Cake(int type, string path, int price, string desc, string ingredients)
        {
            Type = type;
            Thumbnail = path;
            Price = price;
            Description = desc;
            Ingredients = ingredients;
        }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Thumbnail { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public string Ingredients { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual TypeDescription TypeDescription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<OrderDetail> OrderDetails { get; set; }
    }
}
